import Footer from "@/components/Footer";
import Header from "@/components/header/Header";
import { AuthProvider } from "@/provider/AuthProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Header></Header>
          <main className="w-11/12 min-h-[calc(100vh-165px)] mx-auto">{children}</main>
          <Footer></Footer>
        </AuthProvider>
      </body>
    </html>
  );
}
